- name: Docker install and configuration
  hosts: _development
  become: true
  roles: 
    - geerlingguy.docker
  tasks:
    - name: Install pip
      package:
        name: python3-pip
        state: present

    - name: Install docker sdk
      pip:
        name: docker

- name: Postgre Database configuration
  hosts: _ansible_postgresql_dogan
  become: true
  roles:
    - postgre
- name: Nodejs server configuration
  hosts: _ansible_nodejs_dogan
  become: true
  roles:
    - nodejs
- name: React UI Server configuration
  hosts: _ansible_react_dogan
  become: true
  roles:
    - react